import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/Components/Navbar/page'
import 'react-vertical-timeline-component/style.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='Nav'>
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  )
}
