exports.TimeLineElements = [
	{
		id: 1,
		Title: "Uka Tarsadia University.",
		Location: "Surat",
		Desciption: "Engineering About More Science Stuff And Helping Friends.",
		ButtonText: "College Works",
		Date: "2021 - till Date",
		Icon: "School",
		// Image: "../../Images/UTU Logo.png",
		Link: "https://github.com/PATEL96/CollegeWork/",
	},
	{
		id:2,
		Title: "Sangam TechFest",
		Location: "Surat",
		Desciption: "Head Frontend Developer.",
		ButtonText: "Website",
		Date: "Mar 18,2022 - Jun 17,2022",
		Icon: "Work",
		Link: "https://patel96.github.io/SangamTechFest/",
		// Image: "../../Images/Sangam Logo.png",
	},
	{
		id: 3,
		Title: "Python Programmes",
		Location: "Navsari",
		Desciption: "Fun With Python Programmes",
		ButtonText: "Project Link",
		Date: "Jun 30,2020 - till Date",
		Icon: "School",
		Link: "https://github.com/PATEL96/PyhtonPrograms",
		// Image: "../../Images/Pyton Logo.png",
	},
	{
		id: 4,
		Title: "Online Password Generator",
		Location: "Navsari",
		Desciption: "Generate Passwords in Clicks",
		ButtonText: "Website",
		Date: "2020 - till Date",
		Icon: "School",
		Link: "https://patel96.github.io/Passowrd/",
		// Image: "../../Images/Password Logo.ico",
	},
	{
		id: 5,
		Title: "Heat Vawes",
		Location: "Navsari",
		Desciption: "Lead Front End Developer At Heat Vawes.",
		ButtonText: "Poject Link",
		Date: "Mar 1,2023 - Mar28,2023",
		Icon: "Work",
		Link: "https://github.com/PATEL96/heat-vawe-frontend",
		// Image: "../../Images/HeaVawe Logo.png",
	},
	{
		id: 6,
		Title: "DropD Network",
		Location: "Navsari",
		Desciption: "Junior BlockChain Developer at DropD Network.",
		ButtonText: "DropD Network",
		Date: "Nov 29,2022 - till Date",
		Icon: "Work",
		Link: "https://www.dropd.network/",
		// Image: "../../Images/DropD Logo.svg",
	},
]